### PR TITLE
MCMC swap

### PR DESCRIPTION
**Pull request by Nippon2019**

### CODE REVIEW

**Review by InnovativeInventor — APPROVED** [review]

**Review by InnovativeInventor — CHANGES_REQUESTED** [review]
Don't commit input.yaml

**Review by InnovativeInventor — APPROVED** [review]

**Review by echap1 — CHANGES_REQUESTED** [review]
move your code out of src/optimizers/mcmc.rs

**Comment by echap1** [comment]
maybe move your code to src/optimizers/mcmc_swap.rs
this makes the code more organized bc if u dont actually implement the mcmc structures in src/optimizers/mcmc.rs, then it should be in a different module

**Comment by echapman2022** [comment]
also the functions in trait MCMCOptimizerSWAP should just be in impl MCMCSwap since they probably won't be implemented multiple times (this also speeds up code running time)

**Pull request merged**
